# Generated by Django 2.2.16 on 2020-09-27 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='anonymous', max_length=100)),
                ('interests', models.ManyToManyField(to='charityswipe.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=1000)),
                ('interests', models.ManyToManyField(to='charityswipe.Interest')),
            ],
        ),
    ]
